name: Run Insomnia Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Inso CLI
        uses: kong/setup-inso@v1
        with:
          inso-version: 10.3.0  

      - name: Create report folder
        run: mkdir -p insomnia-expandtesting_API/reports

      - name: Run tests and generate report
        run: |
          inso run collection wrk_89cad6 -e env_2823ee --bail --workingDir expandtesting.json --reporter junit ./reports/report.xml
          
      - name: List files in the report directory
        run: ls -l ./reports

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./reports/report.xml
