name: Run Insomnia Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Inso CLI
        uses: kong/setup-inso@v1
        with:
          inso-version: 10.3.0  

      - name: Run tests and generate report
        run: |
          # Run the Inso command with verbose output to debug
          inso run collection wrk_89cad6 -e env_2823ee --bail --workingDir expandtesting.json --reporter junit > result.log

      - name: List current directory to verify report file
        run: ls -l $GITHUB_WORKSPACE

      - name: Exibir conteúdo do log
        run: cat $GITHUB_WORKSPACE/result.log

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: result-log
          path: $GITHUB_WORKSPACE/result.log
