name: Run Insomnia Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Inso CLI
        uses: kong/setup-inso@v1
        with:
          inso-version: 10.3.0  # Use a versão desejada

      - name: Criar pasta de relatórios
        run: mkdir -p insomnia-expandtesting_API/reports

      - name: Executar testes do Insomnia e gerar relatório
        run: |
          inso run collection wrk_89cad6 -e env_2823ee --bail --workingDir expandtesting.json --reporter junit > insomnia-expandtesting_API/reports/test-results.xml
